[[AbstractTrees]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "feb8b2c99359901e295443c9d0c7e711604acf39"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.2.0"

[[Adapt]]
git-tree-sha1 = "182b4f3518a049cd3b67e25102c99b530afeda82"
uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
version = "0.2.0"

[[Arpack]]
deps = ["BinaryProvider", "LinearAlgebra", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "b30209671cd6137070990e2b71178b2335506256"
uuid = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
version = "0.1.4"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "160d5d926e83e0970dd549ad9fe0ac3e8107e83c"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.8"

[[BinaryProvider]]
deps = ["Compat", "Pkg", "SHA"]
git-tree-sha1 = "94dac52c662ca793008fb689e3daf626b6139943"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.3"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "456524c5dc9af774533e4133f9989296053c5bdd"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.2"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Printf", "Reexport", "Test"]
git-tree-sha1 = "cec56a50029f40f4c13e4f25bf84964fde31905a"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.0"

[[CommonSubexpressions]]
deps = ["Test"]
git-tree-sha1 = "efdaf19ab11c7889334ca247ff4c9f7c322817b0"
uuid = "bbf7d656-a473-5ed7-a52c-81e309532950"
version = "0.2.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "c478aec93ea90bb99c307a92df17a76131bf275f"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.0.0"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "a591110d3ac12c9b4d0cec163fcf234baed7f5ac"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.10.0"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffResults]]
deps = ["Compat", "StaticArrays"]
git-tree-sha1 = "db8acf46717b13d6c48deb7a12007c7f85a70cf7"
uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
version = "0.0.3"

[[DiffRules]]
deps = ["Random", "Test"]
git-tree-sha1 = "6b7b910f2b64784420fbb346b27ac39f71030f29"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "0.0.6"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Distributions]]
deps = ["Distributed", "LinearAlgebra", "PDMats", "Printf", "QuadGK", "Random", "SpecialFunctions", "Statistics", "StatsBase", "StatsFuns", "Test"]
git-tree-sha1 = "50791f3d943bebc7945eb76ced54a1fa316b9e74"
uuid = "31c24e10-a181-5473-b8eb-7969acd0382f"
version = "0.16.1"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "53fae3f45b6782dad91e932d941b0bf862110641"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.1"

[[Flux]]
deps = ["AbstractTrees", "Adapt", "Colors", "DiffRules", "ForwardDiff", "GZip", "LinearAlgebra", "MacroTools", "NNlib", "NaNMath", "Reexport", "Requires", "SpecialFunctions", "StatsBase", "ZipFile"]
git-tree-sha1 = "3793a8fe2a10669981f9ce460c9c32c5d4fe304e"
repo-rev = "julia-0.7"
repo-url = "https://github.com/FluxML/Flux.jl.git"
uuid = "587475ba-b771-5e3f-ad9e-33799f191a9c"
version = "0.5.3+"

[[ForwardDiff]]
deps = ["CommonSubexpressions", "DiffResults", "DiffRules", "InteractiveUtils", "LinearAlgebra", "NaNMath", "Random", "SparseArrays", "SpecialFunctions", "StaticArrays", "Test"]
git-tree-sha1 = "91bd8f3deb78e5d03b5c05c3613f135e5c300252"
uuid = "f6369f11-7733-5829-9624-2563aa707210"
version = "0.8.0"

[[GZip]]
deps = ["Compat"]
git-tree-sha1 = "37bd892cb1717e6fdbb82b8d2c7e3cb8ad89adb6"
uuid = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
version = "0.4.0"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "18c17737f3d375b86b495144ba7ab359ab3dca57"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.2"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NNlib]]
deps = ["Libdl", "LinearAlgebra", "MacroTools", "Requires", "Test"]
git-tree-sha1 = "83dd97789dcd7718ae4f62ac7104e575894b7368"
uuid = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
version = "0.4.0"

[[NaNMath]]
git-tree-sha1 = "3b18ebac4cc5f22fe5af9b4aa63210ae4495507a"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.1"

[[PDMats]]
deps = ["Arpack", "LinearAlgebra", "SparseArrays", "SuiteSparse", "Test"]
git-tree-sha1 = "484f7fbb6c382ab6bcfff4d134f9b51fa29ee562"
uuid = "90014a1f-27ba-587c-ab20-58faa44d9150"
version = "0.9.4"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[ProgressMeter]]
deps = ["Compat"]
git-tree-sha1 = "30d3473425cdb13b23ff10dfc7727be8bcc2871a"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "0.5.6"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra", "Test"]
git-tree-sha1 = "d136ea5b320aad2b1a8c3196e642c2282e601660"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.0.0"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[Rmath]]
deps = ["BinaryProvider", "Compat"]
git-tree-sha1 = "b826c44132eaddd34fc635e4541ca1d3507dda71"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.4.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "70840f1a93da48bcc952e71b600f598532372eb0"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.0"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Spec]]
git-tree-sha1 = "c28f4f72b9371d0c842167670cad7b8fb4c0e71b"
repo-rev = "master"
repo-url = "https://github.com/zenna/Spec.jl"
uuid = "526a04b8-654b-11e8-1588-db2a414f95b5"
version = "0.1.0"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "1cf00baba50536d254f02082c90b98d6e4e1f968"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.6.0"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d998a83bc2cd507e12b08203e7523f2e60ac9ee6"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.2"

[[Statistics]]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "515d9c751bc96f9680a2a19f76395ae8ac06a8f5"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.24.0"

[[StatsFuns]]
deps = ["Pkg", "Rmath", "SpecialFunctions", "Test"]
git-tree-sha1 = "d14bb7b03defd2deaa5675646f6783089e0556f0"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
version = "0.7.0"

[[SuiteSparse]]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[URIParser]]
deps = ["Compat", "Unicode"]
git-tree-sha1 = "0f9c5e2d14e03fbd00696f9394e288bdd5adacbc"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.3.1"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[UnicodePlots]]
deps = ["Compat", "StatsBase"]
git-tree-sha1 = "ca93b5cb5338ea776b5b9947eff0fd01560afd3d"
uuid = "b8865327-cd53-5732-bb35-84acbb429228"
version = "0.2.6"

[[ZenUtils]]
deps = ["Spec"]
git-tree-sha1 = "9f39f7ff4a4f97fb40d21fc84764d977e5b0bcac"
repo-rev = "master"
repo-url = "https://github.com/zenna/ZenUtils.jl"
uuid = "8c7a6496-654a-11e8-0e4c-c7dc3dc823b6"
version = "0.1.0"

[[ZipFile]]
deps = ["Compat"]
git-tree-sha1 = "0d40c806c569c651fb4e08f104f33a09086b975f"
uuid = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
version = "0.6.0"
