name = "OmegaMH"
uuid = "89eb2d39-e1f3-436d-870a-9a4679d6d79e"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
InferenceBase = "5213bc24-6d0f-4e1b-8b55-aef4cfc4ccc3"
OmegaCore = "84d23798-d00f-4e9b-a82e-be69778c030a"

[compat]
InferenceBase = "0.1"
OmegaCore = "0.1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Distributions", "Random"]
