name = "OmegaViz"
uuid = "f1502cda-89ab-11e9-143c-c92a03599598"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
Callbacks = "db1e321a-d383-57b4-a664-0144fd54e973"
Lens = "496038af-b016-571c-b31e-8262695ac102"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Omega = "1af16e33-887a-59b3-8344-18f1671b3ade"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
